### ISSUE TITLE
Which IP address is it asking for?

### ISSUE THREAD

**Issue by snowweb** [rikpg/NetWatcher#1]
In the options of NetWatcher, it asks for a comma separated list of IP addresses, but I'm not sure whether this list should be a list of other devices addresses or addresses of the machine that it's running on?

I use DHCP on the network, so either way, I think this might be a bit troublesome. Any advice would be appreciated.

Thanks for the pluggin though. If I can get it to work it will be great! I'm using it on Linux and the installation went without a hitch.

**Comment by rikpg** [comment]
It's a list of the other devices addresses: the target devices that you wish to check whether they're on or off-line.

The list is static, it assumes that you're able know in advance a bunch of ip-addr to be checked. A complete scan that targets a whole range of ip-addresses (and finds out your own) can be implemented and was in mind from the beginning, just let me know a possible usage example and I'll write the code.

Glad you liked it, thanks for the feedback!

**Comment by snowweb** [comment]
Hi Riccardo,

Thanks for your reply and dedication to this plug-in.

The scenario that I'm trying to address by using your plug-in is like 
this... I have a 384Kbps ADSL connection (I live in the Philippines 
where connections speeds are low and costly) and we share this 
connection via a Wifi and ethernet router, where the devices are 
connected using DHCP, among the other household members.

When I'm downloading, often the others find their connections unusable 
because I'm hogging all the bandwidth. I'm happy to reduce my download 
speeds temporarily at those times, but can't really determine when it's 
safe to revert back to unlimited download speeds again, so would like an 
automated solution.

Also, it would be great if it could also help when I'm downloading 
something via HTTP (like watching a video in a browser on the same 
machine or just browsing. It would be great if it could reduce the 
maximum allowable speed for Deluge then too, to make it easier to 
continue browsing.

Ideally, I'd like the plug-in to determine not whether others are 
connected to the network, but whether they are downloading. Especially 
if they are trying to watch a video or download a file, I would like the 
plugin to automatically reduce my maximum allowable speed in Deluge to a 
pre-determined level (which I can set in an option) until the ADSL 
connection is less congested.

I'm not sure how you might accomplish that though? I'm wondering if 
pinging a known IP address on the Internet and measuring the response 
time/latency might be an acceptable way? Perhaps the IP address / or 
hostname to ping, could be configurable in the options too and the 
latency thresh-hold could also be configurable?

When the latency thresh-hold is exceeded, perhaps it should reduce the 
maximum allowable speed to the pre-determined value for a specified 
amount of time, before retesting.

The important thing to note is that it should not be monitoring the 
congestion on the local network, because the LAN never gets congested 
with Internet traffic since the LAN is quite fast in comparison to the 
Internet connection. It's really the Internet connection that it somehow 
needs to monitor for congestion.

Not really sure how programmable this is! But good luck with it if you 
decide to give it a go. I'd love to donate to help you along, but 
unfortunately, I'm working a big project myself and am not yet making 
enough income to keep me afloat at the moment.

Many thanks,

Peter

**Comment by rikpg** [comment]
Hi Peter, you really took the time to explain things, I appreciate it.
Can I ask you to copy and paste your comment as a new issue so that I'll tag it as a feature request and keep things in order by closing this one and not going off topic. It'll be very cool of you!

In the meantime if you like, you can check the develop branch where I impletemented a complete scan so that one doesn't need to know in advance anything. If you'll test it and it works I'll merge it into master.
About the other features I'll explain once we move in the new issue, anyway the short story is that looking at how much band is being used is a nearly impossible thing to achieve and it would just take an awful amount of work: it's a complicated topic, the band limit, insted, can be done and I already put down a mock interface. If you have trouble installing from the develop branch just let me know (in the new issue).

Thanks
Rik
